# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy CI

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/instalytics.ca/Instalytics
            git fetch origin production
            git reset --hard origin/production
            sudo rsync -av --delete /var/www/instalytics.ca/Instalytics/nodePythonApp/ /var/www/instalytics.ca/backend
            cd /var/www/instalytics.ca/backend
            sudo touch /var/www/instalytics.ca/backend/.env
            echo FRONTEND_ADDRESS=https://instalytics.ca | sudo tee -a /var/www/instalytics.ca/backend/.env
            echo MAILER_LOGIN=${{ secrets.MAILER_LOGIN }} | sudo tee -a /var/www/instalytics.ca/backend/.env
            echo MAILER_PASSWORD=${{ secrets.MAILER_PASSWORD }} | sudo tee -a /var/www/instalytics.ca/backend/.env
            echo IG_SCRAPER_LOGIN=${{ secrets.IG_SCRAPER_LOGIN }} | sudo tee -a /var/www/instalytics.ca/backend/.env
            echo IG_SCRAPER_PASSWORD=${{ secrets.IG_SCRAPER_PASSWORD }} | sudo tee -a /var/www/instalytics.ca/backend/.env
            sudo npm install --unsafe-perm
            cd /var/www/instalytics.ca/Instalytics/client
            sudo npm install --unsafe-perm
            sudo touch /var/www/instalytics.ca/Instalytics/client/.env
            echo REACT_APP_BACKEND_ADDRESS=https://instalytics.ca | sudo tee -a /var/www/instalytics.ca/Instalytics/client/.env
            echo REACT_APP_FRONTEND_ADDRESS=https://instalytics.ca | sudo tee -a /var/www/instalytics.ca/Instalytics/client/.env
            sudo npm run build --prefix /var/www/instalytics.ca/Instalytics/client/
            sudo rsync -av --delete /var/www/instalytics.ca/Instalytics/client/build/ /var/www/instalytics.ca/html
            pm2 reload server
            sudo systemctl reload nginx
